repos:
-   repo: https://github.com/ambv/black
    rev: master
    hooks:
    - id: black
      args: [--line-length=100, --safe, --target-version=py38]
      language_version: python3.7
      verbose: true
      exclude: ^lightbus_experiments/
