repos:
-   repo: https://github.com/ambv/black
    rev: master
    hooks:
    - id: black
      args: [--line-length=100, --safe, --py36]
      python_version: python3.6
      verbose: true
      exclude: ^lightbus_experiments/
