sudo: required

env:
- CC_TEST_REPORTER_ID=e0d94e367b5a4a0aeb1b06bd7a1335eac602df0e5fa38557d6a6cffb2b501426

language: python

python:
- "3.6"

services:
- docker

before_install:
- docker build -t lightbus-test -f tests/Dockerfile .
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter

before_script:
- ./cc-test-reporter before-build

script:
- docker run -v `pwd`:/lightbus lightbus-test

after_script:
- ./cc-test-reporter after-build --exit-code TRAVIS_TEST_RESULT
