sudo: required

env:
- CMD="docker run -v `pwd`:/lightbus lightbus-test"

services:
- docker

before_install:
- docker build -t lightbus-test -f tests/Dockerfile .

script:
- $CMD pytest --cov=lightbus

after_script:
- $CMD coveralls
