sudo: required

env:
- CC_TEST_REPORTER_ID=e0d94e367b5a4a0aeb1b06bd7a1335eac602df0e5fa38557d6a6cffb2b501426

# The python language specified here is only used for combining & submitting
# the coverage reports. The testing environment is provided by the docker image
# built below.
language: python
python:
- "3.6"

services:
- docker

before_install:
- docker build -t lightbus-test -f tests/Dockerfile .
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- pip install coverage

before_script:
- ./cc-test-reporter before-build

script:
- docker run -v `pwd`:/lightbus lightbus-test

after_script:
- coverage combine .coverage
- ./cc-test-reporter format-coverage --input-type coverage.py .coverage
- ./cc-test-reporter upload-coverage
