sudo: required

env:
  global:
    - REDIS_URL: redis://redis_a:6379
    - REDIS_URL_B: redis://redis_b:6380

language: python
python:
- "3.6"
- "3.7"
- "3.8"

services:
- docker

before_install:
# Note that the tests need access to the redis-server binary,
# not just network access
- docker up -d db redis_a redis_b
- pip install tox tox-travis coverage coveralls

script:
- tox -- --cov=lightbus

after_script:
- coverage combine .coverage/coverage
- coveralls
