sudo: required

env:
  global:
    - REDIS_URL: redis://localhost:60791
    - REDIS_URL_B: redis://localhost:60792
    - PG_URL: postgres://postgres@localhost:54320/postgres

language: python

matrix:
  include:
    - python: 3.6
      dist: trusty
      sudo: false
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.8-dev
      dist: xenial
      sudo: true
    - python: 3.6
      dist: trusty
      sudo: false
      env: TOXENV=docs
      before_install: pip install tox
      script: tox
      after_script: 
      on:
        branch: master
  allow_failures:
    - python: 3.8-dev

cache:
  directories:
    - .tox

services:
  - docker

before_install:
  # Note that the tests need access to the redis-server binary,
  # not just network access
  - docker-compose -f tests/docker-compose.yaml up -d db redis_a redis_b
  - pip install tox tox-travis coverage coveralls
  - mkdir -p .coverage

script:
  - tox -- --cov=lightbus

after_script:
  - coverage combine .coverage/coverage
  - coveralls
