sudo: required

env:
- CMD="docker run -v `pwd`:/lightbus lightbus-test"

# The python language specified here is only used for combining & submitting
# the coverage reports. The testing environment is provided by the docker image
# built below.
language: python
python:
- "3.6"

services:
- docker

before_install:
- docker build -t lightbus-test -f tests/Dockerfile .

script:
- $CMD pytest --cov=lightbus

after_script:
- coverage combine .coverage
- coveralls
