theme: readthedocs

# Project information
site_name: Lightbus
site_description: RPC & event system for Python 3
site_author: Adam Charnock
site_url: http://lightbus.org

# Repository
repo_name: GitHub
repo_url: https://github.com/adamcharnock/lightbus

theme:
  name: material

  palette:
    primary: 'pink'
    accent: 'indigo'

  static_templates:
    - 404.html

  language: en

  font:
    text: Roboto
    code: Roboto Mono
  favicon: ""
  logo:
    icon: "\uE915"

pages:
  - Introduction: index.md
  - Installation: installation.md
  - Concepts: concepts.md
  - Quick start: quick-start.md
  - Worked example: worked-example.md
  - Typing: typing.md
  - APIs: apis.md
  - Remote prcedure calls: rpcs.md
  - Events: events.md
  - Configuration: configuration.md
  - Schema: schema.md
  - Transports: transports.md
  - Command line use: command-line-use.md
  - Debugging: debugging.md
  - Plugins: plugins.md
  - Contributing: contributing.md

# Extensions
markdown_extensions:
  - meta
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

google_analytics:
  - 'UA-103655163-1'
  - 'auto'
