version: 2.1

workflows:
  version: 2
  tests:
    jobs:
      - test-36
      - test-37
    # Disabling 3.8 until either psycopg2 has a binary for it,
    # or until we remove the need for psycopg2 in testing
    #  - test-38
      - combine_coverage_reports:
          requires:
            - test-36
            - test-37
#            - test-38

  build_and_deploy_docs:
    jobs:
      - docs:
          filters:
            branches:
              only:
                - master
                - run-in-executor
jobs:
  test-36: &test-template
    docker:
      - image: circleci/python:3.6
        environment:
          PIPENV_VENV_IN_PROJECT: true
      - image: postgres:9.6.2
      - image: redis:5

    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-3-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            pipenv install --ignore-pipfile --dev
            mkdir -p .coverage
            pipenv run pytest --cov=lightbus
            pipenv run coveralls
            mv .coverage/coverage$CIRCLE_BUILD_NUM
          environment:
            PIPENV_VENV_IN_PROJECT: true

      - persist_to_workspace:
          root: .coverage
          paths:
            - coverage$CIRCLE_BUILD_NUM

      - save_cache:
          key: deps-2-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"

  test-37:
    <<: *test-template
    docker:
      - image: circleci/python:3.7
        environment:
          PIPENV_VENV_IN_PROJECT: true
      - image: postgres:9.6.2
      - image: redis:5

  test-38:
    <<: *test-template
    docker:
      - image: circleci/python:3.8-rc
        environment:
          PIPENV_VENV_IN_PROJECT: true
      - image: postgres:9.6.2
      - image: redis:5

  docs:
    docker:
      - image: circleci/python:3.6
        environment:
          PIPENV_VENV_IN_PROJECT: true

    steps:
      - add_ssh_keys:
          fingerprints:
            - "cf:7f:13:98:f7:41:bf:92:af:ff:52:ed:6c:35:8f:65"

      - checkout

      - restore_cache:
          keys:
            - deps-3-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            pipenv install --ignore-pipfile --dev
            pipenv run mkdocs gh-deploy --force --message="Automated build by CircleCI [ci skip]"
          environment:
            PIPENV_VENV_IN_PROJECT: true

      - save_cache:
          key: deps-2-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"

  combine_coverage_reports:
    docker:
      - image: circleci/python:3.6
        environment:
          PIPENV_VENV_IN_PROJECT: true

    steps:
      - checkout
      - attach_workspace:
          at: .coverage
      - run:
          command: |
            pipenv install coveralls coverage
            pipenv run coverage combine .coverage/coverage*
            pipenv run coveralls
      - run:
          command: |
            apk add curl
            curl -k https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN -d "payload[build_num]=$CIRCLE_BUILD_NUM&payload[status]=done"
