version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
        environment:
          PIPENV_VENV_IN_PROJECT: true
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
      - image: redis:5

    steps:
      - checkout
      - restore_cache:
          keys: deps-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            pip install tox tox-travis coverage coveralls
            mkdir -p .coverage
      - run:
          command: |
            tox -- --cov=lightbus

      - save_cache:
          keys: deps-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
            - "/usr/local/lib/python3.7/site-packages"
