version: 2
workflows:
  version: 2
  tests:
    jobs:
      - test-3.6
      - test-3.7
    # Disabling 3.8 until either psycopg2 has a binary for it,
    # or until we remove the need for psycopg2 in testing
    #  - test-3.8

  build_and_deploy_docs:
    jobs:
      - docs:
        filters:
          branches:
            only: master
jobs:
  test-3.6: &test-template
    docker:
      - image: circleci/python:3.6
        environment:
          PIPENV_VENV_IN_PROJECT: true
      - image: postgres:9.6.2
      - image: redis:5

    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-3-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            pipenv install --ignore-pipfile --dev
            mkdir -p .coverage
            pipenv run pytest
          environment:
            PIPENV_VENV_IN_PROJECT: true

      - save_cache:
          key: deps-2-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"

  test-3.7:
    <<: *test-template
    docker:
      - image: circleci/python:3.7
        environment:
          PIPENV_VENV_IN_PROJECT: true
      - image: postgres:9.6.2
      - image: redis:5

  test-3.8:
    <<: *test-template
    docker:
      - image: circleci/python:3.8-rc
        environment:
          PIPENV_VENV_IN_PROJECT: true
      - image: postgres:9.6.2
      - image: redis:5

  docs:
    docker:
      - image: circleci/python:3.6
        environment:
          PIPENV_VENV_IN_PROJECT: true

    steps:
      - add_ssh_keys:
          fingerprints:
            - "cf:7f:13:98:f7:41:bf:92:af:ff:52:ed:6c:35:8f:65"
      - run:
          command: |
            pipenv install --ignore-pipfile --dev
            mkdocs gh-deploy --force
          environment:
            PIPENV_VENV_IN_PROJECT: true

