version: 2
jobs:
  build:
    docker:
      - image: themattrix/tox
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
      - image: redis:5

    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            pip install --user --upgrade pip
            pip install --user tox coverage coveralls
            mkdir -p .coverage
          environment:
            PATH: ~/.local/bin:$PATH
      - run:
          command: |
            tox -- --cov=lightbus

      - save_cache:
          key: deps-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
            - "/usr/local/lib/python3.7/site-packages"
